01:
	go run 01-RaceCondition.go

02:
	go run 02-Deadlock.go

03: 
	go run 03-Deadlock.go	

04: 
	go run 04-LiveLock.go	

05: 
	go run 05-Skeleton.go	

06: 
	go run 06-Simulate.go	

07: 
	go run 07-WaitGroup.go		

08: 
	go run 08-WaitGroup.go	

09: 
	go run 09-SyncCond.go		

10: 
	go run 10-SyncCond.go	

11: 
	go run 11-SyncCond.go	

12: 
	go run 12-SyncCond.go		

13: 
	go run 13-SyncCond.go		

14: 
	go run 14-SyncCond.go		

15: 
	go run 15-SyncOnce.go		

16: 
	go run 16-SyncMutex.go		

17: 
	go run 17-SyncRWMutex.go		

18: 
	go run 18-CliUtility.go		

19: 
	go run 19-CliUtility.go	

20:
	go run 	20-ConcurrentPorts.go

21:
	go run 	21-ConcurrentPorts.go

22:
	go run 	22-SyncMap.go

23:
	go run 	23-ConcurrentPorts.go

24:
	go run 	24-Pool.go

25Client:
	go run 	25-PoolClient.go

25Server:
	go run 	25-PoolServer.go

26Client:
	go run 	26-PoolClient.go

26Server:
	go run 	26-PoolServer.go

